# myapp/docker-compose.dev.yml
version: "3.7"

services:
  php-fpm:
    build:
      context: ./php-fpm
    restart: unless-stopped
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - MONGODB_URL=${MONGODB_URL}
    volumes:
      - ./src:/var/www
      - ./src/var/cache:/var/www/var/cache
    networks:
      - default
      - mongo_external_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    networks:
      - default
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # mongo:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     MONGODB_DB: ${MONGODB_DB}
  #     MONGODB_USER: ${MONGODB_USER}
  #     MONGODB_PASSWORD: ${MONGODB_PASSWORD}
  #   volumes:
  #     - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro

networks:
  default:
  mongo_external_network:
    external: true
    name: mongodb-learning_default # Replace with the actual network name
