api_platform:
  title: Hello API Platform
  version: 1.0.0
  doctrine:
    enabled: false
  doctrine_mongodb_odm:
    enabled: true
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
