security:
  providers:
    app_user_provider:
      mongodb:
        class: App\Document\User
        property: email
    # used to reload user from session & other features (e.g. switch_user)
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

    # main:
    #   stateless: true
    #   provider: app_user_provider
    #   json_login:
    #     check_path: /api/login
    #     username_path: email
    #     password_path: password
    #   logout:
    #     path: app_logout
    #   entry_point: json_login
    #   jwt: ~

  access_control:
    - { path: ^/api/auth, roles: PUBLIC_ACCESS }
    - { path: ^/api?, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: ROLE_USER }
